/*
 * Generated by gdbus-codegen 2.32.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "generated-code.h"

#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:MultimediaSampleplayer
 * @title: MultimediaSampleplayer
 * @short_description: Generated C code for the org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer ---- */

static const _ExtendedGDBusArgInfo _multimedia_sampleplayer_method_info_play_IN_ARG_arg0 =
{
  {
    -1,
    "arg0",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _multimedia_sampleplayer_method_info_play_IN_ARG_pointers[] =
{
  &_multimedia_sampleplayer_method_info_play_IN_ARG_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _multimedia_sampleplayer_method_info_play =
{
  {
    -1,
    "play",
    (GDBusArgInfo **) &_multimedia_sampleplayer_method_info_play_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-play",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _multimedia_sampleplayer_method_info_pointers[] =
{
  &_multimedia_sampleplayer_method_info_play,
  NULL
};

static const _ExtendedGDBusArgInfo _multimedia_sampleplayer_signal_info_eof_ARG_state =
{
  {
    -1,
    "state",
    "d",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _multimedia_sampleplayer_signal_info_eof_ARG_pointers[] =
{
  &_multimedia_sampleplayer_signal_info_eof_ARG_state,
  NULL
};

static const _ExtendedGDBusSignalInfo _multimedia_sampleplayer_signal_info_eof =
{
  {
    -1,
    "eof",
    (GDBusArgInfo **) &_multimedia_sampleplayer_signal_info_eof_ARG_pointers,
    NULL
  },
  "eof"
};

static const _ExtendedGDBusSignalInfo * const _multimedia_sampleplayer_signal_info_pointers[] =
{
  &_multimedia_sampleplayer_signal_info_eof,
  NULL
};

static const _ExtendedGDBusPropertyInfo _multimedia_sampleplayer_property_info_state =
{
  {
    -1,
    "State",
    "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "state",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _multimedia_sampleplayer_property_info_pointers[] =
{
  &_multimedia_sampleplayer_property_info_state,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _multimedia_sampleplayer_interface_info =
{
  {
    -1,
    "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer",
    (GDBusMethodInfo **) &_multimedia_sampleplayer_method_info_pointers,
    (GDBusSignalInfo **) &_multimedia_sampleplayer_signal_info_pointers,
    (GDBusPropertyInfo **) &_multimedia_sampleplayer_property_info_pointers,
    NULL
  },
  "sampleplayer",
};


/**
 * multimedia_sampleplayer_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
multimedia_sampleplayer_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_multimedia_sampleplayer_interface_info;
}

/**
 * multimedia_sampleplayer_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #MultimediaSampleplayer interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
multimedia_sampleplayer_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "state");
  return property_id_begin - 1;
}



/**
 * MultimediaSampleplayer:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link>.
 */

/**
 * MultimediaSampleplayerIface:
 * @parent_iface: The parent interface.
 * @handle_play: Handler for the #MultimediaSampleplayer::handle-play signal.
 * @get_state: Getter for the #MultimediaSampleplayer:state property.
 * @eof: Handler for the #MultimediaSampleplayer::eof signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link>.
 */

static void
multimedia_sampleplayer_default_init (MultimediaSampleplayerIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * MultimediaSampleplayer::handle-play:
   * @object: A #MultimediaSampleplayer.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_arg0: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.play">play()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call multimedia_sampleplayer_complete_play() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-play",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MultimediaSampleplayerIface, handle_play),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_BOOLEAN);

  /* GObject signals for received D-Bus signals: */
  /**
   * MultimediaSampleplayer::eof:
   * @object: A #MultimediaSampleplayer.
   * @arg_state: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.eof">"eof"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("eof",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MultimediaSampleplayerIface, eof),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_DOUBLE);

  /* GObject properties for D-Bus properties: */
  /**
   * MultimediaSampleplayer:state:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.State">"State"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("state", "State", "State", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

typedef MultimediaSampleplayerIface MultimediaSampleplayerInterface;
G_DEFINE_INTERFACE (MultimediaSampleplayer, multimedia_sampleplayer, G_TYPE_OBJECT);

/**
 * multimedia_sampleplayer_get_state: (skip)
 * @object: A #MultimediaSampleplayer.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.State">"State"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use multimedia_sampleplayer_dup_state() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
multimedia_sampleplayer_get_state (MultimediaSampleplayer *object)
{
  return MULTIMEDIA_SAMPLEPLAYER_GET_IFACE (object)->get_state (object);
}

/**
 * multimedia_sampleplayer_dup_state: (skip)
 * @object: A #MultimediaSampleplayer.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.State">"State"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
multimedia_sampleplayer_dup_state (MultimediaSampleplayer *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "state", &value, NULL);
  return value;
}

/**
 * multimedia_sampleplayer_set_state: (skip)
 * @object: A #MultimediaSampleplayer.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.State">"State"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
multimedia_sampleplayer_set_state (MultimediaSampleplayer *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "state", value, NULL);
}

/**
 * multimedia_sampleplayer_emit_eof:
 * @object: A #MultimediaSampleplayer.
 * @arg_state: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.eof">"eof"</link> D-Bus signal.
 */
void
multimedia_sampleplayer_emit_eof (
    MultimediaSampleplayer *object,
    gdouble arg_state)
{
  g_signal_emit_by_name (object, "eof", arg_state);
}

/**
 * multimedia_sampleplayer_call_play:
 * @proxy: A #MultimediaSampleplayerProxy.
 * @arg_arg0: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.play">play()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call multimedia_sampleplayer_call_play_finish() to get the result of the operation.
 *
 * See multimedia_sampleplayer_call_play_sync() for the synchronous, blocking version of this method.
 */
void
multimedia_sampleplayer_call_play (
    MultimediaSampleplayer *proxy,
    gboolean arg_arg0,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "play",
    g_variant_new ("(b)",
                   arg_arg0),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * multimedia_sampleplayer_call_play_finish:
 * @proxy: A #MultimediaSampleplayerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to multimedia_sampleplayer_call_play().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with multimedia_sampleplayer_call_play().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
multimedia_sampleplayer_call_play_finish (
    MultimediaSampleplayer *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * multimedia_sampleplayer_call_play_sync:
 * @proxy: A #MultimediaSampleplayerProxy.
 * @arg_arg0: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.play">play()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See multimedia_sampleplayer_call_play() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
multimedia_sampleplayer_call_play_sync (
    MultimediaSampleplayer *proxy,
    gboolean arg_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "play",
    g_variant_new ("(b)",
                   arg_arg0),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * multimedia_sampleplayer_complete_play:
 * @object: A #MultimediaSampleplayer.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.play">play()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
multimedia_sampleplayer_complete_play (
    MultimediaSampleplayer *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * MultimediaSampleplayerProxy:
 *
 * The #MultimediaSampleplayerProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MultimediaSampleplayerProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MultimediaSampleplayerProxy.
 */

struct _MultimediaSampleplayerProxyPrivate
{
  GData *qdata;
};

static void multimedia_sampleplayer_proxy_iface_init (MultimediaSampleplayerIface *iface);

G_DEFINE_TYPE_WITH_CODE (MultimediaSampleplayerProxy, multimedia_sampleplayer_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (MULTIMEDIA_TYPE_SAMPLEPLAYER, multimedia_sampleplayer_proxy_iface_init));

static void
multimedia_sampleplayer_proxy_finalize (GObject *object)
{
  MultimediaSampleplayerProxy *proxy = MULTIMEDIA_SAMPLEPLAYER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (multimedia_sampleplayer_proxy_parent_class)->finalize (object);
}

static void
multimedia_sampleplayer_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _multimedia_sampleplayer_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
multimedia_sampleplayer_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  error = NULL;
  if (!g_dbus_proxy_call_finish (proxy, res, &error))
    {
      g_warning ("Error setting property `%s' on interface org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
}

static void
multimedia_sampleplayer_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _multimedia_sampleplayer_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) multimedia_sampleplayer_proxy_set_property_cb, (gpointer) info);
  g_variant_unref (variant);
}

static void
multimedia_sampleplayer_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_multimedia_sampleplayer_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], MULTIMEDIA_TYPE_SAMPLEPLAYER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MULTIMEDIA_TYPE_SAMPLEPLAYER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
multimedia_sampleplayer_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  MultimediaSampleplayerProxy *proxy = MULTIMEDIA_SAMPLEPLAYER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_multimedia_sampleplayer_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_multimedia_sampleplayer_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *
multimedia_sampleplayer_proxy_get_state (MultimediaSampleplayer *object)
{
  MultimediaSampleplayerProxy *proxy = MULTIMEDIA_SAMPLEPLAYER_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "State");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static void
multimedia_sampleplayer_proxy_init (MultimediaSampleplayerProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, MULTIMEDIA_TYPE_SAMPLEPLAYER_PROXY, MultimediaSampleplayerProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), multimedia_sampleplayer_interface_info ());
}

static void
multimedia_sampleplayer_proxy_class_init (MultimediaSampleplayerProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (MultimediaSampleplayerProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = multimedia_sampleplayer_proxy_finalize;
  gobject_class->get_property = multimedia_sampleplayer_proxy_get_property;
  gobject_class->set_property = multimedia_sampleplayer_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = multimedia_sampleplayer_proxy_g_signal;
  proxy_class->g_properties_changed = multimedia_sampleplayer_proxy_g_properties_changed;


  multimedia_sampleplayer_override_properties (gobject_class, 1);
}

static void
multimedia_sampleplayer_proxy_iface_init (MultimediaSampleplayerIface *iface)
{
  iface->get_state = multimedia_sampleplayer_proxy_get_state;
}

/**
 * multimedia_sampleplayer_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call multimedia_sampleplayer_proxy_new_finish() to get the result of the operation.
 *
 * See multimedia_sampleplayer_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
multimedia_sampleplayer_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MULTIMEDIA_TYPE_SAMPLEPLAYER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer", NULL);
}

/**
 * multimedia_sampleplayer_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to multimedia_sampleplayer_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with multimedia_sampleplayer_proxy_new().
 *
 * Returns: (transfer full) (type MultimediaSampleplayerProxy): The constructed proxy object or %NULL if @error is set.
 */
MultimediaSampleplayer *
multimedia_sampleplayer_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MULTIMEDIA_SAMPLEPLAYER (ret);
  else
    return NULL;
}

/**
 * multimedia_sampleplayer_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See multimedia_sampleplayer_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MultimediaSampleplayerProxy): The constructed proxy object or %NULL if @error is set.
 */
MultimediaSampleplayer *
multimedia_sampleplayer_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MULTIMEDIA_TYPE_SAMPLEPLAYER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer", NULL);
  if (ret != NULL)
    return MULTIMEDIA_SAMPLEPLAYER (ret);
  else
    return NULL;
}


/**
 * multimedia_sampleplayer_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like multimedia_sampleplayer_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call multimedia_sampleplayer_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See multimedia_sampleplayer_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
multimedia_sampleplayer_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MULTIMEDIA_TYPE_SAMPLEPLAYER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer", NULL);
}

/**
 * multimedia_sampleplayer_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to multimedia_sampleplayer_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with multimedia_sampleplayer_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type MultimediaSampleplayerProxy): The constructed proxy object or %NULL if @error is set.
 */
MultimediaSampleplayer *
multimedia_sampleplayer_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MULTIMEDIA_SAMPLEPLAYER (ret);
  else
    return NULL;
}

/**
 * multimedia_sampleplayer_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like multimedia_sampleplayer_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See multimedia_sampleplayer_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MultimediaSampleplayerProxy): The constructed proxy object or %NULL if @error is set.
 */
MultimediaSampleplayer *
multimedia_sampleplayer_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MULTIMEDIA_TYPE_SAMPLEPLAYER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer", NULL);
  if (ret != NULL)
    return MULTIMEDIA_SAMPLEPLAYER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * MultimediaSampleplayerSkeleton:
 *
 * The #MultimediaSampleplayerSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MultimediaSampleplayerSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MultimediaSampleplayerSkeleton.
 */

struct _MultimediaSampleplayerSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_multimedia_sampleplayer_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], MULTIMEDIA_TYPE_SAMPLEPLAYER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MULTIMEDIA_TYPE_SAMPLEPLAYER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_multimedia_sampleplayer_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_multimedia_sampleplayer_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_multimedia_sampleplayer_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_multimedia_sampleplayer_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _multimedia_sampleplayer_skeleton_vtable =
{
  _multimedia_sampleplayer_skeleton_handle_method_call,
  _multimedia_sampleplayer_skeleton_handle_get_property,
  _multimedia_sampleplayer_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
multimedia_sampleplayer_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return multimedia_sampleplayer_interface_info ();
}

static GDBusInterfaceVTable *
multimedia_sampleplayer_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_multimedia_sampleplayer_skeleton_vtable;
}

static GVariant *
multimedia_sampleplayer_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_multimedia_sampleplayer_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _multimedia_sampleplayer_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _multimedia_sampleplayer_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _multimedia_sampleplayer_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _multimedia_sampleplayer_emit_changed (gpointer user_data);

static void
multimedia_sampleplayer_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _multimedia_sampleplayer_emit_changed (skeleton);
}

static void
_multimedia_sampleplayer_on_signal_eof (
    MultimediaSampleplayer *object,
    gdouble arg_state)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(d)",
                   arg_state));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer", "eof",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void multimedia_sampleplayer_skeleton_iface_init (MultimediaSampleplayerIface *iface);
G_DEFINE_TYPE_WITH_CODE (MultimediaSampleplayerSkeleton, multimedia_sampleplayer_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (MULTIMEDIA_TYPE_SAMPLEPLAYER, multimedia_sampleplayer_skeleton_iface_init));

static void
multimedia_sampleplayer_skeleton_finalize (GObject *object)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (object);
  guint n;
  for (n = 0; n < 1; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (multimedia_sampleplayer_skeleton_parent_class)->finalize (object);
}

static void
multimedia_sampleplayer_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_multimedia_sampleplayer_emit_changed (gpointer user_data)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *l;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (l = connections; l != NULL; l = l->next)
        {
          GDBusConnection *connection = l->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_multimedia_sampleplayer_schedule_emit_changed (MultimediaSampleplayerSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
multimedia_sampleplayer_skeleton_notify (GObject      *object,
  GParamSpec *pspec)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _multimedia_sampleplayer_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
multimedia_sampleplayer_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _multimedia_sampleplayer_schedule_emit_changed (skeleton, _multimedia_sampleplayer_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
multimedia_sampleplayer_skeleton_init (MultimediaSampleplayerSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, MULTIMEDIA_TYPE_SAMPLEPLAYER_SKELETON, MultimediaSampleplayerSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 1);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRING);
}

static const gchar *
multimedia_sampleplayer_skeleton_get_state (MultimediaSampleplayer *object)
{
  MultimediaSampleplayerSkeleton *skeleton = MULTIMEDIA_SAMPLEPLAYER_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
multimedia_sampleplayer_skeleton_class_init (MultimediaSampleplayerSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (MultimediaSampleplayerSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = multimedia_sampleplayer_skeleton_finalize;
  gobject_class->get_property = multimedia_sampleplayer_skeleton_get_property;
  gobject_class->set_property = multimedia_sampleplayer_skeleton_set_property;
  gobject_class->notify       = multimedia_sampleplayer_skeleton_notify;


  multimedia_sampleplayer_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = multimedia_sampleplayer_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = multimedia_sampleplayer_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = multimedia_sampleplayer_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = multimedia_sampleplayer_skeleton_dbus_interface_get_vtable;
}

static void
multimedia_sampleplayer_skeleton_iface_init (MultimediaSampleplayerIface *iface)
{
  iface->eof = _multimedia_sampleplayer_on_signal_eof;
  iface->get_state = multimedia_sampleplayer_skeleton_get_state;
}

/**
 * multimedia_sampleplayer_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link>.
 *
 * Returns: (transfer full) (type MultimediaSampleplayerSkeleton): The skeleton object.
 */
MultimediaSampleplayer *
multimedia_sampleplayer_skeleton_new (void)
{
  return MULTIMEDIA_SAMPLEPLAYER (g_object_new (MULTIMEDIA_TYPE_SAMPLEPLAYER_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for Object, ObjectProxy and ObjectSkeleton
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:MultimediaObject
 * @title: MultimediaObject
 * @short_description: Specialized GDBusObject types
 *
 * This section contains the #MultimediaObject, #MultimediaObjectProxy, and #MultimediaObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces.
 */

/**
 * MultimediaObject:
 *
 * The #MultimediaObject type is a specialized container of interfaces.
 */

/**
 * MultimediaObjectIface:
 * @parent_iface: The parent interface.
 *
 * Virtual table for the #MultimediaObject interface.
 */

static void
multimedia_object_default_init (MultimediaObjectIface *iface)
{
  /**
   * MultimediaObject:sampleplayer:
   *
   * The #MultimediaSampleplayer instance corresponding to the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("sampleplayer", "sampleplayer", "sampleplayer", MULTIMEDIA_TYPE_SAMPLEPLAYER, G_PARAM_READWRITE|G_PARAM_STATIC_STRINGS));

}

typedef MultimediaObjectIface MultimediaObjectInterface;
G_DEFINE_INTERFACE_WITH_CODE (MultimediaObject, multimedia_object, G_TYPE_OBJECT, g_type_interface_add_prerequisite (g_define_type_id, G_TYPE_DBUS_OBJECT));

/**
 * multimedia_object_get_sampleplayer:
 * @object: A #MultimediaObject.
 *
 * Gets the #MultimediaSampleplayer instance for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link> on @object, if any.
 *
 * Returns: (transfer full): A #MultimediaSampleplayer that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
MultimediaSampleplayer *multimedia_object_get_sampleplayer (MultimediaObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer");
  if (ret == NULL)
    return NULL;
  return MULTIMEDIA_SAMPLEPLAYER (ret);
}


/**
 * multimedia_object_peek_sampleplayer: (skip)
 * @object: A #MultimediaObject.
 *
 * Like multimedia_object_get_sampleplayer() but doesn't increase the reference count on the returned object.
 *
 * <warning>It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.</warning>
 *
 * Returns: (transfer none): A #MultimediaSampleplayer or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
MultimediaSampleplayer *multimedia_object_peek_sampleplayer (MultimediaObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return MULTIMEDIA_SAMPLEPLAYER (ret);
}


static void
multimedia_object_notify (GDBusObject *object, GDBusInterface *interface)
{
  g_object_notify (G_OBJECT (object), ((_ExtendedGDBusInterfaceInfo *) g_dbus_interface_get_info (interface))->hyphen_name);
}

/**
 * MultimediaObjectProxy:
 *
 * The #MultimediaObjectProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MultimediaObjectProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MultimediaObjectProxy.
 */

static void
multimedia_object_proxy__multimedia_object_iface_init (MultimediaObjectIface *iface)
{
}

static void
multimedia_object_proxy__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = multimedia_object_notify;
  iface->interface_removed = multimedia_object_notify;
}


G_DEFINE_TYPE_WITH_CODE (MultimediaObjectProxy, multimedia_object_proxy, G_TYPE_DBUS_OBJECT_PROXY,
                         G_IMPLEMENT_INTERFACE (MULTIMEDIA_TYPE_OBJECT, multimedia_object_proxy__multimedia_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, multimedia_object_proxy__g_dbus_object_iface_init));

static void
multimedia_object_proxy_init (MultimediaObjectProxy *object)
{
}

static void
multimedia_object_proxy_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
}

static void
multimedia_object_proxy_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  MultimediaObjectProxy *object = MULTIMEDIA_OBJECT_PROXY (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
multimedia_object_proxy_class_init (MultimediaObjectProxyClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = multimedia_object_proxy_set_property;
  gobject_class->get_property = multimedia_object_proxy_get_property;

  g_object_class_override_property (gobject_class, 1, "sampleplayer");
}

/**
 * multimedia_object_proxy_new:
 * @connection: A #GDBusConnection.
 * @object_path: An object path.
 *
 * Creates a new proxy object.
 *
 * Returns: (transfer full): The proxy object.
 */
MultimediaObjectProxy *
multimedia_object_proxy_new (GDBusConnection *connection,
  const gchar *object_path)
{
  g_return_val_if_fail (G_IS_DBUS_CONNECTION (connection), NULL);
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return MULTIMEDIA_OBJECT_PROXY (g_object_new (MULTIMEDIA_TYPE_OBJECT_PROXY, "g-connection", connection, "g-object-path", object_path, NULL));
}

/**
 * MultimediaObjectSkeleton:
 *
 * The #MultimediaObjectSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MultimediaObjectSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MultimediaObjectSkeleton.
 */

static void
multimedia_object_skeleton__multimedia_object_iface_init (MultimediaObjectIface *iface)
{
}


static void
multimedia_object_skeleton__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = multimedia_object_notify;
  iface->interface_removed = multimedia_object_notify;
}

G_DEFINE_TYPE_WITH_CODE (MultimediaObjectSkeleton, multimedia_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON,
                         G_IMPLEMENT_INTERFACE (MULTIMEDIA_TYPE_OBJECT, multimedia_object_skeleton__multimedia_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, multimedia_object_skeleton__g_dbus_object_iface_init));

static void
multimedia_object_skeleton_init (MultimediaObjectSkeleton *object)
{
}

static void
multimedia_object_skeleton_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  MultimediaObjectSkeleton *object = MULTIMEDIA_OBJECT_SKELETON (gobject);
  GDBusInterfaceSkeleton *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (MULTIMEDIA_IS_SAMPLEPLAYER (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer");
        }
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
multimedia_object_skeleton_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  MultimediaObjectSkeleton *object = MULTIMEDIA_OBJECT_SKELETON (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
multimedia_object_skeleton_class_init (MultimediaObjectSkeletonClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = multimedia_object_skeleton_set_property;
  gobject_class->get_property = multimedia_object_skeleton_get_property;

  g_object_class_override_property (gobject_class, 1, "sampleplayer");
}

/**
 * multimedia_object_skeleton_new:
 * @object_path: An object path.
 *
 * Creates a new skeleton object.
 *
 * Returns: (transfer full): The skeleton object.
 */
MultimediaObjectSkeleton *
multimedia_object_skeleton_new (const gchar *object_path)
{
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return MULTIMEDIA_OBJECT_SKELETON (g_object_new (MULTIMEDIA_TYPE_OBJECT_SKELETON, "g-object-path", object_path, NULL));
}

/**
 * multimedia_object_skeleton_set_sampleplayer:
 * @object: A #MultimediaObjectSkeleton.
 * @interface_: (allow-none): A #MultimediaSampleplayer or %NULL to clear the interface.
 *
 * Sets the #MultimediaSampleplayer instance for the D-Bus interface <link linkend="gdbus-interface-org-gtk-GDBus-Multimedia-ObjectManager-Sampleplayer.top_of_page">org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer</link> on @object.
 */
void multimedia_object_skeleton_set_sampleplayer (MultimediaObjectSkeleton *object, MultimediaSampleplayer *interface_)
{
  g_object_set (G_OBJECT (object), "sampleplayer", interface_, NULL);
}


/* ------------------------------------------------------------------------
 * Code for ObjectManager client
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:MultimediaObjectManagerClient
 * @title: MultimediaObjectManagerClient
 * @short_description: Generated GDBusObjectManagerClient type
 *
 * This section contains a #GDBusObjectManagerClient that uses multimedia_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc.
 */

/**
 * MultimediaObjectManagerClient:
 *
 * The #MultimediaObjectManagerClient structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MultimediaObjectManagerClientClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MultimediaObjectManagerClient.
 */

G_DEFINE_TYPE (MultimediaObjectManagerClient, multimedia_object_manager_client, G_TYPE_DBUS_OBJECT_MANAGER_CLIENT);

static void
multimedia_object_manager_client_init (MultimediaObjectManagerClient *manager)
{
}

static void
multimedia_object_manager_client_class_init (MultimediaObjectManagerClientClass *klass)
{
}

/**
 * multimedia_object_manager_client_get_proxy_type:
 * @manager: A #GDBusObjectManagerClient.
 * @object_path: The object path of the remote object (unused).
 * @interface_name: (allow-none): Interface name of the remote object or %NULL to get the object proxy #GType.
 * @user_data: User data (unused).
 *
 * A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy<!-- -->- and #GDBusProxy<!-- -->-derived types.
 *
 * Returns: A #GDBusProxy<!-- -->-derived #GType if @interface_name is not %NULL, otherwise the #GType for #MultimediaObjectProxy.
 */
GType
multimedia_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data)
{
  static gsize once_init_value = 0;
  static GHashTable *lookup_hash;
  GType ret;

  if (interface_name == NULL)
    return MULTIMEDIA_TYPE_OBJECT_PROXY;
  if (g_once_init_enter (&once_init_value))
    {
      lookup_hash = g_hash_table_new (g_str_hash, g_str_equal);
      g_hash_table_insert (lookup_hash, "org.gtk.GDBus.Multimedia.ObjectManager.Sampleplayer", GSIZE_TO_POINTER (MULTIMEDIA_TYPE_SAMPLEPLAYER_PROXY));
      g_once_init_leave (&once_init_value, 1);
    }
  ret = (GType) GPOINTER_TO_SIZE (g_hash_table_lookup (lookup_hash, interface_name));
  if (ret == (GType) 0)
    ret = G_TYPE_DBUS_PROXY;
  return ret;
}

/**
 * multimedia_object_manager_client_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates #GDBusObjectManagerClient using multimedia_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call multimedia_object_manager_client_new_finish() to get the result of the operation.
 *
 * See multimedia_object_manager_client_new_sync() for the synchronous, blocking version of this constructor.
 */
void
multimedia_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (MULTIMEDIA_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", multimedia_object_manager_client_get_proxy_type, NULL);
}

/**
 * multimedia_object_manager_client_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to multimedia_object_manager_client_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with multimedia_object_manager_client_new().
 *
 * Returns: (transfer full) (type MultimediaObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
multimedia_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * multimedia_object_manager_client_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates #GDBusObjectManagerClient using multimedia_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See multimedia_object_manager_client_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MultimediaObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
multimedia_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (MULTIMEDIA_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", multimedia_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/**
 * multimedia_object_manager_client_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like multimedia_object_manager_client_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call multimedia_object_manager_client_new_for_bus_finish() to get the result of the operation.
 *
 * See multimedia_object_manager_client_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
multimedia_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (MULTIMEDIA_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", multimedia_object_manager_client_get_proxy_type, NULL);
}

/**
 * multimedia_object_manager_client_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to multimedia_object_manager_client_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with multimedia_object_manager_client_new_for_bus().
 *
 * Returns: (transfer full) (type MultimediaObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
multimedia_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * multimedia_object_manager_client_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like multimedia_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See multimedia_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MultimediaObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
multimedia_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (MULTIMEDIA_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", multimedia_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


