#!/bin/sh
# this script sets the runtime environment variables
export LD_LIBRARY_PATH=.:release:${LD_LIBRARY_PATH}
export PATH=.:release:${PATH}

# Start whatever application is requested
target=$1;

shift
exec env ${target} "$@"


