#!/bin/sh
# this script sets the runtime environment variables
export LD_LIBRARY_PATH=bin:${LD_LIBRARY_PATH}
export PATH=.:bin:${PATH}

# Start whatever application is requested
target=$1;

shift
exec env ${target} "$@"


